import { expect, test, type Page } from '@playwright/test';
import type { CompanyResponse, EmployeeResponse, MenuCategory, PageResponse, PriceTierRecord, SettingsResponse } from '@fernleaf/contracts';

test.use({ timezoneId: 'America/Los_Angeles' });

async function login(page: Page) {
  await page.goto('/login');
  await page.getByLabel('Email address').fill('admin@test.com');
  await page.getByLabel('Password', { exact: true }).fill('Test@1234');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
}
const unique = () => `Browser ${Date.now()} ${Math.floor(Math.random() * 10000)}`;
async function createCompany(page: Page, name: string, domain: string) {
  await page.goto('/companies');
  await page.getByRole('button', { name: 'Add company', exact: true }).click();
  const form = page.getByRole('form', { name: 'Add company', exact: true });
  await form.getByLabel('Company name', { exact: false }).fill(name);
  await form.getByLabel('Billing name', { exact: false }).fill(name);
  await form.getByLabel('Billing email', { exact: false }).fill(`billing@${domain}`);
  await form.getByLabel('Billing contact name', { exact: false }).fill('Browser accounts');
  await form.getByLabel('Billing address', { exact: false }).fill('42 Browser Street, Bengaluru');
  await form.getByLabel('Company email domains', { exact: false }).fill(domain);
  await form.getByLabel('First employee / owner name', { exact: false }).fill(`${name} owner`);
  await form.getByLabel('First employee / owner email', { exact: false }).fill(`owner@${domain}`);
  await form.getByLabel('Street address', { exact: false }).fill('42 Browser Street');
  await form.getByLabel('City', { exact: false }).fill('Bengaluru');
  await form.getByLabel('State / region', { exact: false }).fill('Karnataka');
  await form.getByLabel('Postal code', { exact: false }).fill('560001');
  await form.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(form).toHaveCount(0);
  const result = await page.request.get(`/api/v1/companies?search=${encodeURIComponent(name)}`);
  const list = await result.json() as PageResponse<CompanyResponse>;
  expect(list.items).toHaveLength(1);
  return list.items[0];
}

test('Admin creates and edits catalogue records, ordered reusable groups and reference values', async ({ page }) => {
  await login(page);
  const label = unique();
  await page.getByRole('link', { name: 'Catalogue', exact: true }).click();
  await page.getByRole('tab', { name: 'Reference lists', exact: true }).click();
  await page.getByLabel('List', { exact: true }).selectOption('KITCHEN_STATION');
  await page.getByRole('button', { name: 'Add reference value', exact: true }).click();
  const reference = page.getByRole('form', { name: 'Add reference value', exact: true });
  await reference.getByLabel('Name', { exact: false }).fill(`${label} station`);
  await reference.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('cell', { name: `${label} station`, exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Options', exact: true }).click();
  await page.getByRole('button', { name: 'Add option', exact: true }).click();
  const option = page.getByRole('form', { name: 'Add option', exact: true });
  await option.getByLabel('Name', { exact: false }).fill(`${label} rice`);
  await option.getByLabel('Description', { exact: false }).fill('Reusable browser test grain.');
  await option.getByLabel('Cost (USD)', { exact: false }).fill('0.55');
  await option.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('cell', { name: `${label} rice`, exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Dishes', exact: true }).click();
  await page.getByRole('button', { name: 'Add dish', exact: true }).click();
  const dish = page.getByRole('form', { name: 'Add dish', exact: true });
  await dish.getByLabel('Name', { exact: false }).fill(`${label} lunch`);
  await dish.getByLabel('Description', { exact: false }).fill('Browser test dish.');
  await dish.getByLabel('Cost (USD)', { exact: false }).fill('2.11');
  await dish.getByLabel('SKU', { exact: false }).fill(label.replaceAll(' ', '-'));
  await dish.getByLabel('Kitchen station', { exact: true }).selectOption({ label: `${label} station` });
  await dish.getByLabel('Minimum order quantity', { exact: true }).fill('2');
  await dish.getByRole('button', { name: 'Save changes', exact: true }).click();
  const row = page.getByRole('row').filter({ has: page.getByText(`${label} lunch`, { exact: true }) });
  await expect(row).toContainText('$2.11');
  await row.getByRole('button', { name: 'Option groups', exact: true }).click();
  await page.getByRole('button', { name: 'Add option group', exact: true }).click();
  await page.getByLabel('Group 1 name', { exact: true }).fill('Grain choice');
  await page.getByLabel('Add option to group 1', { exact: true }).selectOption({ label: `${label} rice` });
  await page.getByRole('button', { name: 'Save option groups', exact: true }).click();
  await expect(page.getByRole('status').last()).toHaveText('Changes saved.');
  await row.getByRole('button', { name: 'Edit', exact: true }).click();
  const edit = page.getByRole('form', { name: 'Edit dish', exact: true });
  await edit.getByLabel('Active', { exact: true }).uncheck();
  await edit.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(row).toContainText('Inactive');
});

test('Admin bulk pricing uses server derivation, exact explicit amounts and missing filters', async ({ page }, testInfo) => {
  await login(page);
  const label = unique();
  await page.getByRole('link', { name: 'Pricing', exact: true }).click();
  await page.getByRole('button', { name: 'Add price tier', exact: true }).click();
  const form = page.getByRole('form', { name: 'Add price tier', exact: true });
  await form.getByLabel('Name', { exact: false }).fill(label);
  await form.getByLabel('Derivation rule', { exact: false }).selectOption('COST');
  await form.getByLabel('Ratio numerator', { exact: false }).fill('1');
  await form.getByLabel('Ratio denominator', { exact: false }).fill('1');
  await form.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(form).toHaveCount(0);
  await page.getByLabel('Price tier', { exact: true }).selectOption({ label });
  const rice = page.getByRole('row').filter({ has: page.getByText('Roasted vegetable rice box', { exact: true }) });
  await expect(rice).toContainText('$2.15');
  await page.getByLabel('Override for Roasted vegetable rice box', { exact: true }).fill('2.11');
  await page.getByRole('button', { name: 'Save price overrides', exact: true }).click();
  await expect(rice).toContainText('$2.11');
  await expect(rice).toContainText('explicit');
  await page.getByLabel('Override for Roasted vegetable rice box', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Save price overrides', exact: true }).click();
  await expect(rice).toContainText('$2.15');
  const tiers = await (await page.request.get('/api/v1/price-tiers')).json() as PageResponse<PriceTierRecord>;
  const missingTier = tiers.items.find((tier) => tier.name === 'Company manual')!;
  await page.getByLabel('Price tier', { exact: true }).selectOption(missingTier.id);
  await page.getByLabel('Missing prices only', { exact: true }).check();
  await expect(page.getByRole('cell', { name: 'Missing price', exact: true }).first()).toBeVisible();
  const screenshot = testInfo.outputPath('pricing-matrix.png');
  await page.screenshot({ path: screenshot, fullPage: true });
  await testInfo.attach('pricing-matrix', { path: screenshot, contentType: 'image/png' });
});

test('Company owner, hidden items, missing prices and secret links agree with employee preview', async ({ page }, testInfo) => {
  await login(page);
  const name = unique();
  const company = await createCompany(page, name, `browser-${Date.now()}.example`);
  const owner = company.employees.find((employee) => employee.id === company.ownerEmployeeId)!;
  await page.goto('/menu');
  await page.getByRole('tab', { name: 'Employee preview', exact: true }).click();
  await page.getByLabel('Employee', { exact: true }).selectOption(owner.id);
  await expect(page.getByRole('heading', { name: 'Roasted vegetable rice box', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: /Seasonal soup/ })).toHaveCount(0);
  await expect(page.getByText(/Dish has no price in the selected tier/)).toBeVisible();
  const secretLink = page.getByRole('link', { name: /Preview Chef/ });
  await expect(secretLink).toBeVisible();
  await secretLink.click();
  await expect(page.getByRole('heading', { name: /preview lunch/ })).toBeVisible();
  await page.goto('/companies');
  const row = page.getByRole('row').filter({ has: page.getByText(name, { exact: true }) });
  await row.getByRole('button', { name: 'Edit', exact: true }).click();
  const edit = page.getByRole('form', { name: 'Edit company', exact: true });
  await edit.getByLabel('Hidden menu items', { exact: true }).selectOption({ label: 'Roasted vegetable rice box · Lunch boxes' });
  const categories = await (await page.request.get('/api/v1/categories')).json() as PageResponse<MenuCategory>;
  const secret = categories.items.find((category) => category.secret)!;
  await edit.getByLabel('Hidden categories', { exact: true }).selectOption(secret.id);
  await edit.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(edit).toHaveCount(0);
  await page.goto('/menu');
  await page.getByRole('tab', { name: 'Employee preview', exact: true }).click();
  await page.getByLabel('Employee', { exact: true }).selectOption(owner.id);
  await expect(page.getByRole('heading', { name: 'Roasted vegetable rice box', exact: true })).toHaveCount(0);
  await expect(page.getByText(/Menu item is hidden for this company/)).toBeVisible();
  await page.goto(`/menu/preview/${owner.id}/categories/${secret.id}`);
  await expect(page.getByRole('heading', { name: /preview lunch/ })).toHaveCount(0);
  await expect(page.getByText(/Category is hidden for this company/)).toBeVisible();
  await page.goto('/employees');
  await page.getByLabel('Company filter', { exact: true }).selectOption(company.id);
  await page.getByRole('button', { name: 'Add employee', exact: true }).click();
  const employeeForm = page.getByRole('form', { name: 'Add employee', exact: true });
  await employeeForm.getByLabel('Name', { exact: false }).fill(`${name} colleague`);
  await employeeForm.getByLabel('Employee email', { exact: false }).fill(`colleague@${company.domains[0]}`);
  await employeeForm.getByLabel('May choose delivery address', { exact: true }).check();
  await employeeForm.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(employeeForm).toHaveCount(0);
  const ownerRow = page.getByRole('row').filter({ has: page.getByText(owner.name, { exact: true }) });
  await ownerRow.getByRole('button', { name: 'Transfer', exact: true }).click();
  const transfer = page.getByRole('form', { name: `Transfer ${owner.name}`, exact: true });
  await transfer.getByLabel('Destination company', { exact: false }).selectOption('20000000-0000-4000-8000-000000000001');
  await transfer.getByLabel('Replacement owner in current company', { exact: false }).selectOption({ label: `${name} colleague · colleague@${company.domains[0]}` });
  await transfer.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(transfer).toHaveCount(0);
  const updated = await (await page.request.get(`/api/v1/companies/${company.id}`)).json() as CompanyResponse;
  expect(updated.ownerEmployeeId).not.toBe(owner.id);
  const moved = await (await page.request.get(`/api/v1/employees/${owner.id}`)).json() as EmployeeResponse;
  expect(moved.companyId).toBe('20000000-0000-4000-8000-000000000001');
  const screenshot = testInfo.outputPath('employees.png');
  await page.screenshot({ path: screenshot, fullPage: true });
  await testInfo.attach('employees', { path: screenshot, contentType: 'image/png' });
});

test('Admin edits persisted settings and previews the kitchen cutoff independently of browser timezone', async ({ page }) => {
  await login(page);
  const original = await (await page.request.get('/api/v1/settings')).json() as SettingsResponse;
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  const form = page.getByRole('form', { name: 'Edit kitchen defaults', exact: true });
  await form.getByLabel('At-risk threshold (minutes)', { exact: false }).fill(String(original.riskThresholdMinutes + 1));
  await form.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Changes saved.' })).toBeVisible();
  const saved = await (await page.request.get('/api/v1/settings')).json() as SettingsResponse;
  expect(saved.riskThresholdMinutes).toBe(original.riskThresholdMinutes + 1);
  await page.getByLabel('Delivery date', { exact: true }).fill('2026-10-07');
  await page.getByRole('button', { name: 'Preview cutoff', exact: true }).click();
  await expect(page.getByText('Cutoff in Asia/Kolkata', { exact: true })).toBeVisible();
  await expect(page.getByText('No company selected', { exact: true })).toBeVisible();
  await form.getByLabel('At-risk threshold (minutes)', { exact: false }).fill(String(original.riskThresholdMinutes));
  await form.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(form.getByLabel('At-risk threshold (minutes)', { exact: false })).toHaveValue(String(original.riskThresholdMinutes));
});
