'use client';

import Link from 'next/link';
import { useState } from 'react';
import { DROP_STATUSES, type CustomDeliveryAddress, type DeliveryDropResponse, type DriverChoice, type OperationalOrderResponse } from '@fernleaf/contracts';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { useSession } from '@/features/auth/session-provider';
import { textValue } from '@/features/configuration/common';
import { OperationsFeedback, OperationsHeading, OperationsState, RiskLabel, stateLabel, timeLabel, useOperationsMutation, useOperationsResource } from './common';
import styles from './operations.module.css';

export function DeliveryDropScreen({ dropId, driver = false }: { dropId: string; driver?: boolean }) {
  const resource = useOperationsResource<DeliveryDropResponse>(`${driver ? '/driver/drops' : '/drops'}/${dropId}`);
  const drop = resource.data;
  return <><OperationsHeading title={driver ? 'Your delivery stop' : 'Delivery group'} description={driver ? 'Deliver all meals in this stop together. Completion records the current time and updates every member order.' : 'All member orders share one company, physical address and delivery instant. Dispatch and delivery actions apply to the entire group.'} />
    <div className={styles.toolbar}><Link className="button button-secondary" href={driver ? '/today' : drop ? `/dispatch?date=${drop.deliveryDate}` : '/dispatch'}>{driver ? 'Back to my stops' : 'Back to dispatch'}</Link><Button variant="secondary" onClick={resource.refresh}>Refresh delivery group</Button></div>
    <OperationsState loading={resource.loading} failure={resource.failure} refresh={resource.refresh} />
    {drop && <><Card className={styles.card}><div className={styles.topline}><h2>{drop.companyName}</h2><span className="status-pill">{stateLabel(drop.status)}</span></div><ol className={styles.steps} aria-label="Delivery progress">{DROP_STATUSES.map((status) => <li key={status} className={drop.status === status ? styles.current : undefined} aria-current={drop.status === status ? 'step' : undefined}>{stateLabel(status)}</li>)}</ol><p>{drop.orderCount} order(s) · {drop.quantity} meals · Driver: {drop.driver?.name ?? 'Unassigned'}</p><h3>{drop.address.label}</h3><p className={styles.address}>{[drop.address.line1, drop.address.line2, `${drop.address.city}, ${drop.address.region} ${drop.address.postalCode}`, drop.address.country].filter(Boolean).join('\n')}</p><p>Driver instructions: {drop.driverInstructions || 'None recorded'}</p><div className={styles.pills}><span className={styles.muted}>Kitchen</span><RiskLabel risk={drop.kitchenRisk} /><span className={styles.muted}>Dispatch</span><RiskLabel risk={drop.dispatchRisk} /></div><dl className={styles.values}><div><dt>Current delivery target</dt><dd>{timeLabel(drop.deliveryAt)}</dd></div><div><dt>Original target at departure</dt><dd>{timeLabel(drop.targetAtDeparture)}</dd></div><div><dt>Planned kitchen ready</dt><dd>{timeLabel(drop.plannedKitchenReadyAt)}</dd></div><div><dt>Planned dispatch ready</dt><dd>{timeLabel(drop.plannedDispatchReadyAt)}</dd></div><div><dt>Last recorded kitchen ready</dt><dd>{timeLabel(drop.kitchenReadyAt)}</dd></div><div><dt>Last recorded dispatch ready</dt><dd>{timeLabel(drop.dispatchReadyAt)}</dd></div><div><dt>Departed</dt><dd>{timeLabel(drop.departedAt)}</dd></div><div><dt>Delivered</dt><dd>{timeLabel(drop.deliveredAt)}</dd></div><div><dt>Delivery timing outcome</dt><dd>{drop.onTime === null ? 'Unknown — no completed delivery with a valid departure target' : drop.onTime ? 'On time' : 'Late'}</dd></div></dl><p className={styles.muted}>Status determines current readiness. Previously recorded actual times remain visible after a correction; delivery timing uses the target captured at departure.</p>{drop.note && <p>Delivery note: {drop.note}</p>}<DropActions key={drop.id} drop={drop} driver={driver} refresh={resource.refresh} /></Card>
      <Card className={styles.card}><h2>Meals in this group</h2><p>Every order below belongs to this delivery group. Meal quantities are recorded purchases; cancelled members are excluded.</p><div className={styles.units}>{drop.orders.map((order) => <OperationalOrder key={order.id} order={order} driver={driver} />)}</div></Card>
      {!driver && <Card className={styles.card}><h2>Delivery group history</h2><ol className={styles.choices}>{drop.events.map((event) => <li key={event.id}><strong>{stateLabel(event.type)}</strong> · {timeLabel(event.createdAt)} · {event.actorName}{['DRIVER_ASSIGNED', 'DRIVER_REASSIGNED'].includes(event.type) && typeof event.details.driverName === 'string' && <p>Driver: {typeof event.details.beforeDriverName === 'string' ? event.details.beforeDriverName : 'Unassigned'} → {event.details.driverName}</p>}{event.reason && <p>Reason: {event.reason}</p>}</li>)}</ol>{!drop.events.length && <p>No group events recorded.</p>}</Card>}
    </>}
  </>;
}

function OperationalOrder({ order, driver }: { order: OperationalOrderResponse; driver: boolean }) {
  return <article className={styles.unit} aria-label={`Member order ${order.id}`}><div className={styles.topline}><strong>Order #{order.number}</strong><span className="status-pill">{stateLabel(order.status)}</span></div><h3>{order.employee.name}</h3><p>{order.quantity} meals · Packaging: {order.packaging?.name ?? 'None recorded'}</p><p>Contact: {order.employee.phone ? <a href={`tel:${order.employee.phone}`}>{order.employee.phone}</a> : 'Phone not recorded'} · {order.employee.email}</p><p>Preparation: {order.prepUnits.filter((unit) => unit.status === 'DONE').length} of {order.prepUnits.length} combinations complete</p><ul className={styles.choices}>{order.prepUnits.map((unit) => <li key={unit.id}>{unit.quantity} × {unit.dish.name} · {stateLabel(unit.status)}{unit.selections.length > 0 && <span> · {unit.selections.map((selection) => `${selection.groupName}: ${selection.optionName}`).join('; ')}</span>}{unit.allergyWarnings.length > 0 && <p className="allergy-warning">Allergen warning: {unit.allergyWarnings.join(', ')}</p>}</li>)}</ul>{!driver && <p className={styles.muted}>Kitchen ready: {timeLabel(order.kitchenReadyAt)}</p>}</article>;
}

function DropActions({ drop, driver, refresh }: { drop: DeliveryDropResponse; driver: boolean; refresh: () => void }) {
  const { session } = useSession();
  const canDispatch = !driver && session?.permissions.includes('dispatch.assign');
  const departed = drop.status === 'OUT_FOR_DELIVERY' || drop.status === 'DELIVERED';
  const command = useOperationsMutation();
  async function transition(action: 'dispatch-ready' | 'depart') {
    if (await command.send<DeliveryDropResponse>(`/drops/${drop.id}/${action}`, { version: drop.version })) refresh();
  }
  const canDeliver = drop.status === 'OUT_FOR_DELIVERY' && (driver ? session?.permissions.includes('deliveries.complete.own') : session?.permissions.includes('deliveries.complete'));
  return <><OperationsFeedback failure={command.failure} refresh={() => { command.clearFailure(); refresh(); }} />{canDispatch && !departed && <div className={styles.correction}><h3>Dispatch steps</h3><DriverAssignment drop={drop} refresh={refresh} /><div className="form-actions"><Button type="button" variant="secondary" disabled={command.pending || drop.status !== 'KITCHEN_READY'} onClick={() => void transition('dispatch-ready')}>Mark dispatch ready</Button>{session?.permissions.includes('dispatch.depart') && <Button type="button" disabled={command.pending || drop.status !== 'DISPATCH_READY' || !drop.driver} onClick={() => void transition('depart')}>Depart delivery</Button>}</div><p className={styles.muted}>{drop.status === 'AWAITING_KITCHEN' ? 'Every member order must finish preparation before dispatch readiness.' : drop.status === 'KITCHEN_READY' ? 'Check packaging and driver assignment, then mark the group dispatch ready.' : 'Assign an active driver before departure.'}</p></div>}{!driver && drop.status === 'OUT_FOR_DELIVERY' && session?.user.role === 'ADMIN' && <details className={styles.correction}><summary>Admin travelling driver reassignment</summary><p>Choose another active Driver and record why the travelling group changes hands. Departure time and the original delivery target remain unchanged. A delivered group retains its recorded driver.</p><DriverAssignment drop={drop} refresh={refresh} travelling /></details>}{canDeliver && <DeliverForm drop={drop} driver={driver} refresh={refresh} />}{!driver && departed && session?.permissions.includes('orders.override') && <CorrectDropForm key={`${drop.id}-${drop.version}`} drop={drop} refresh={refresh} />}</>;
}

function DriverAssignment({ drop, refresh, travelling = false }: { drop: DeliveryDropResponse; refresh: () => void; travelling?: boolean }) {
  const choices = useOperationsResource<DriverChoice[]>('/drops/drivers');
  const [selection, setSelection] = useState<{ id: string; edited: boolean }>({ id: '', edited: false });
  const driverId = selection.edited ? selection.id : drop.driver?.id ?? '';
  const command = useOperationsMutation();
  async function submit(form: FormData) {
    if (await command.send<DeliveryDropResponse>(`/drops/${drop.id}/assign`, { version: drop.version, driverId, ...(travelling ? { reason: textValue(form, 'reason') } : {}) })) {
      setSelection({ id: driverId, edited: false }); refresh();
    }
  }
  return <form aria-label={travelling ? 'Reassign travelling driver' : 'Assign delivery driver'} onSubmit={(event) => { event.preventDefault(); void submit(new FormData(event.currentTarget)); }}><label className="form-field" htmlFor="drop-driver"><span id="drop-driver-label">Delivery driver</span><select id="drop-driver" aria-labelledby="drop-driver-label" required value={driverId} onChange={(event) => setSelection({ id: event.target.value, edited: true })}><option value="">Choose an active Driver</option>{driverId && !choices.data?.some((choice) => choice.id === driverId) && <option value={driverId}>{drop.driver?.id === driverId ? drop.driver.name : 'Selected driver'} (not in active choices)</option>}{choices.data?.map((choice) => <option key={choice.id} value={choice.id}>{choice.displayName}</option>)}</select></label>{travelling && <label className="form-field" htmlFor="driver-reassignment-reason">Driver reassignment reason<textarea id="driver-reassignment-reason" name="reason" required maxLength={2000} rows={3} /></label>}<OperationsState loading={choices.loading} failure={choices.failure} refresh={choices.refresh} /><OperationsFeedback failure={command.failure} refresh={() => { command.clearFailure(); refresh(); }} /><div className="form-actions"><Button variant="secondary" disabled={command.pending || choices.loading || !driverId || travelling && driverId === drop.driver?.id}>{travelling ? 'Reassign travelling driver' : 'Assign driver'}</Button></div></form>;
}

function DeliverForm({ drop, driver, refresh }: { drop: DeliveryDropResponse; driver: boolean; refresh: () => void }) {
  const command = useOperationsMutation();
  async function submit(form: FormData) {
    const note = textValue(form, 'note');
    if (await command.send<DeliveryDropResponse>(`${driver ? '/driver/drops' : '/drops'}/${drop.id}/deliver`, { version: drop.version, ...(note ? { note } : {}) })) refresh();
  }
  return <form className={styles.correction} aria-label="Complete grouped delivery" onSubmit={(event) => { event.preventDefault(); void submit(new FormData(event.currentTarget)); }}><h3>Complete this stop</h3><p>Mark all {drop.orderCount} member order(s) delivered together. The service records the actual delivery time now.</p><label className="form-field" htmlFor="delivery-note">Delivery note (optional)<textarea id="delivery-note" name="note" maxLength={2000} rows={3} placeholder="Reception contact or a delivery exception" /></label><OperationsFeedback failure={command.failure} refresh={refresh} /><div className="form-actions"><Button disabled={command.pending}>{command.pending ? 'Recording delivery...' : 'Mark delivered'}</Button></div></form>;
}

function localTime(value: string): string {
  return new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value));
}
function CorrectDropForm({ drop, refresh }: { drop: DeliveryDropResponse; refresh: () => void }) {
  const command = useOperationsMutation();
  async function submit(form: FormData) {
    const address: CustomDeliveryAddress = { label: textValue(form, 'label'), line1: textValue(form, 'line1'), line2: textValue(form, 'line2') || null, city: textValue(form, 'city'), region: textValue(form, 'region'), postalCode: textValue(form, 'postalCode'), country: textValue(form, 'country') };
    if (await command.send<DeliveryDropResponse>(`/drops/${drop.id}/correct`, { version: drop.version, reason: textValue(form, 'reason'), address, deliveryDate: textValue(form, 'date'), deliveryTime: textValue(form, 'time') })) refresh();
  }
  return <details className={styles.correction}><summary>Admin drop-wide correction</summary><p className={`${styles.notice} ${styles.warning}`}>The meals have departed together. This address/time correction updates every member order below, preserves purchased amounts and actual history, and keeps the original departure target for the delivery outcome.</p><h3>All affected orders</h3><ul className={styles.choices}>{drop.orders.map((order) => <li key={order.id}>Order #{order.number} · {order.employee.name} · {order.quantity} meals · {stateLabel(order.status)}</li>)}</ul><form aria-label="Correct entire delivery group" onSubmit={(event) => { event.preventDefault(); void submit(new FormData(event.currentTarget)); }}><div className="form-grid"><label className="form-field" htmlFor="correct-date">Corrected delivery date<input id="correct-date" name="date" type="date" required defaultValue={drop.deliveryDate} /></label><label className="form-field" htmlFor="correct-time">Corrected delivery time<input id="correct-time" name="time" type="time" required defaultValue={localTime(drop.deliveryAt)} /></label>{(['label', 'line1', 'line2', 'city', 'region', 'postalCode', 'country'] as const).map((field) => <label className="form-field" htmlFor={`correct-${field}`} key={field}>{({ label: 'Address label', line1: 'Address line 1', line2: 'Address line 2 (optional)', city: 'City', region: 'Region', postalCode: 'Postal code', country: 'Country' })[field]}<input id={`correct-${field}`} name={field} required={field !== 'line2'} maxLength={field === 'line1' || field === 'line2' ? 300 : 100} defaultValue={drop.address[field] ?? ''} /></label>)}</div><label className="form-field" htmlFor="correct-reason">Drop correction reason<textarea id="correct-reason" name="reason" required maxLength={2000} rows={3} /></label><label className={styles.checkbox}><input type="checkbox" required />I reviewed every affected order in this group</label><OperationsFeedback failure={command.failure} refresh={refresh} /><div className="form-actions"><Button disabled={command.pending}>{command.pending ? 'Correcting group...' : 'Correct entire group'}</Button></div></form></details>;
}
