'use client';

import Link from 'next/link';
import { useState } from 'react';
import type { CompanyAddressResponse, CompanyResponse, DriverChoiceResponse, PriceTierRecord } from '@fernleaf/contracts';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { useReferences } from './catalogue';
import { checked, DataState, EditorForm, Feedback, Heading, lines, nullableValue, numberValue, Pagination, selections, textValue, useMutation, useResource, useChoiceResource, type FieldDefinition, type Paged, type Values } from './common';

export const calendarFields: FieldDefinition[] = [{ name: 'workingDays', label: 'Working days', type: 'days' }, { name: 'holidays', label: 'Holidays', type: 'textarea', help: 'One local date per line (YYYY-MM-DD). Company calendars determine allowed delivery dates; the kitchen calendar alone counts cutoff days.', placeholder: '2026-12-25' }];
const addressFields: FieldDefinition[] = [{ name: 'label', label: 'Address label', required: true }, { name: 'line1', label: 'Street address', required: true }, { name: 'line2', label: 'Address line 2' }, { name: 'city', label: 'City', required: true }, { name: 'region', label: 'State / region', required: true }, { name: 'postalCode', label: 'Postal code', required: true }, { name: 'country', label: 'Country', required: true }];
function addressBody(form: FormData, prefix = '') { return { label: textValue(form, `${prefix}label`), line1: textValue(form, `${prefix}line1`), line2: nullableValue(form, `${prefix}line2`), city: textValue(form, `${prefix}city`), region: textValue(form, `${prefix}region`), postalCode: textValue(form, `${prefix}postalCode`), country: textValue(form, `${prefix}country`) }; }

export function CompaniesScreen() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [editing, setEditing] = useState<CompanyResponse | null>(null);
  const [open, setOpen] = useState(false);
  const [addressCompany, setAddressCompany] = useState<CompanyResponse | null>(null);
  const resource = useResource<Paged<CompanyResponse>>(`/companies?page=${page}&pageSize=20&search=${encodeURIComponent(search)}`);
  return <><Heading title="Companies" description="Delivery calendars, billing details, owners and company-specific menu restrictions." /><div className="section-toolbar"><h2>Company directory</h2><Button onClick={() => { setEditing(null); setOpen(true); }}>Add company</Button></div><form className="filter-bar" aria-label="Search companies" onSubmit={(event) => { event.preventDefault(); setSearch(textValue(new FormData(event.currentTarget), 'q')); setPage(1); }}><label htmlFor="company-search">Search companies</label><input id="company-search" name="q" type="search" /><Button variant="secondary">Search</Button><Button type="button" variant="ghost" onClick={resource.refresh}>Refresh</Button></form><DataState loading={resource.loading} failure={resource.failure} refresh={resource.refresh} />{resource.data && <Card><div className="table-scroll"><table><thead><tr><th>Company</th><th>Domains</th><th>Owner</th><th>Delivery default</th><th>Actions</th></tr></thead><tbody>{resource.data.items.map((company) => <tr key={company.id}><td><strong>{company.name}</strong><span className="cell-note">{company.active ? 'Active' : 'Inactive'}</span></td><td>{company.domains.join(', ') || 'No domains'}</td><td>{company.employees.find((employee) => employee.id === company.ownerEmployeeId)?.name ?? 'Missing owner'}</td><td>{company.deliveryTime} · {company.deliveryMinutes} min travel</td><td><Button variant="ghost" onClick={() => { setEditing(company); setOpen(true); }}>Edit</Button><Button variant="ghost" onClick={() => setAddressCompany(company)}>Addresses</Button><Link className="button button-ghost" href={`/employees?companyId=${company.id}`}>Employees</Link></td></tr>)}</tbody></table>{!resource.data.items.length && <p className="empty-copy">No matching companies. Add a company with its first employee owner and delivery address.</p>}</div><Pagination page={page} total={resource.data.total} pageSize={resource.data.pageSize} onPage={setPage} /></Card>}{open && <CompanyEditor key={editing?.id ?? 'new'} company={editing} onClose={() => setOpen(false)} onSaved={() => { resource.refresh(); setOpen(false); }} />}{addressCompany && <AddressManager key={addressCompany.id} companyId={addressCompany.id} name={addressCompany.name} onClose={() => setAddressCompany(null)} onSaved={resource.refresh} />}</>;
}
function CompanyEditor({ company, onClose, onSaved }: { company: CompanyResponse | null; onClose: () => void; onSaved: () => void }) {
  const tiers = useChoiceResource<PriceTierRecord>('/price-tiers?page=1&pageSize=100');
  const categories = useChoiceResource<{ id: string; name: string }>('/categories?page=1&pageSize=100');
  const items = useChoiceResource<{ id: string; dish: { name: string }; category: { name: string } }>('/menu-items?page=1&pageSize=100');
  const drivers = useResource<DriverChoiceResponse[]>('/companies/drivers');
  const references = useReferences();
  const action = useMutation();
  const fields: FieldDefinition[] = [
    { name: 'name', label: 'Company name', required: true }, { name: 'phone', label: 'Phone' },
    { name: 'billingName', label: 'Billing name', required: true }, { name: 'billingEmail', label: 'Billing email', type: 'email', required: true }, { name: 'billingContactName', label: 'Billing contact name', required: true }, { name: 'billingAddress', label: 'Billing address', type: 'textarea', required: true },
    { name: 'domains', label: 'Company email domains', type: 'textarea', required: true, help: 'One domain per line. Lowercase normalization and unique, non-public-domain validation are performed by the kitchen service.', placeholder: 'example-company.test' },
    { name: 'priceTierId', label: 'Company price tier', type: 'select', choices: (tiers.data?.items ?? []).filter((tier) => tier.active || tier.id === company?.priceTierId).map((tier) => ({ value: tier.id, label: tier.name })), help: 'Leave blank to use the kitchen default. Missing prices within the selected tier do not fall back.' },
    { name: 'deliveryTime', label: 'Default delivery time', type: 'time', required: true }, { name: 'deliveryMinutes', label: 'Travel time (minutes)', type: 'number', min: 0, required: true },
    { name: 'packagingId', label: 'Default packaging', type: 'select', choices: (references.data ?? []).filter((value) => value.kind === 'PACKAGING_TYPE').map((value) => ({ value: value.id, label: value.name })) },
    { name: 'defaultDriverId', label: 'Default driver', type: 'select', choices: (drivers.data ?? []).map((driver) => ({ value: driver.id, label: driver.displayName })) },
    { name: 'driverInstructions', label: 'Driver instructions', type: 'textarea' }, ...calendarFields, { name: 'active', label: 'Active company', type: 'checkbox' },
    ...(company ? [
      { name: 'ownerEmployeeId', label: 'Company owner', type: 'select' as const, required: true, choices: company.employees.filter((employee) => employee.active).map((employee) => ({ value: employee.id, label: `${employee.name} · ${employee.email}` })), help: 'The owner must be an active employee of this company.' },
      { name: 'defaultAddressId', label: 'Default delivery address', type: 'select' as const, required: true, choices: company.addresses.filter((address) => address.active).map((address) => ({ value: address.id, label: `${address.label} · ${address.line1}` })) },
      { name: 'hiddenCategoryIds', label: 'Hidden categories', type: 'multiple' as const, choices: (categories.data?.items ?? []).map((category) => ({ value: category.id, label: category.name })), help: 'Hold Ctrl (Windows) or Command to select multiple. Secret links still respect these restrictions.' },
      { name: 'hiddenMenuItemIds', label: 'Hidden menu items', type: 'multiple' as const, choices: (items.data?.items ?? []).map((item) => ({ value: item.id, label: `${item.dish.name} · ${item.category.name}` })) },
    ] : [{ name: 'ownerName', label: 'First employee / owner name', required: true }, { name: 'ownerEmail', label: 'First employee / owner email', type: 'email' as const, required: true }, ...addressFields.map((field) => ({ ...field, name: `address_${field.name}` }))]),
  ];
  const initial: Values = company ? { ...company, domains: company.domains.join('\n'), holidays: company.holidays.join('\n') } as unknown as Values : { workingDays: [1, 2, 3, 4, 5], deliveryTime: '12:30', deliveryMinutes: 30, active: true, address_country: 'India', address_label: 'Main office' };
  if (!tiers.data || !categories.data || !items.data || !drivers.data || !references.data) return <DataState loading={tiers.loading || categories.loading || items.loading || drivers.loading || references.loading} failure={tiers.failure ?? categories.failure ?? items.failure ?? drivers.failure ?? references.failure} refresh={() => { tiers.refresh(); categories.refresh(); items.refresh(); drivers.refresh(); references.refresh(); }} />;
  function submit(form: FormData) {
    const common = { name: textValue(form, 'name'), phone: nullableValue(form, 'phone'), billingName: textValue(form, 'billingName'), billingEmail: textValue(form, 'billingEmail'), billingContactName: textValue(form, 'billingContactName'), billingAddress: textValue(form, 'billingAddress'), domains: lines(form, 'domains'), priceTierId: nullableValue(form, 'priceTierId'), deliveryTime: textValue(form, 'deliveryTime'), deliveryMinutes: numberValue(form, 'deliveryMinutes'), packagingId: nullableValue(form, 'packagingId'), defaultDriverId: nullableValue(form, 'defaultDriverId'), driverInstructions: textValue(form, 'driverInstructions'), workingDays: selections(form, 'workingDays').map(Number), holidays: lines(form, 'holidays'), active: checked(form, 'active') };
    const body = company ? { ...common, version: company.version, ownerEmployeeId: textValue(form, 'ownerEmployeeId'), defaultAddressId: textValue(form, 'defaultAddressId'), hiddenCategoryIds: selections(form, 'hiddenCategoryIds'), hiddenMenuItemIds: selections(form, 'hiddenMenuItemIds') } : { ...common, owner: { name: textValue(form, 'ownerName'), email: textValue(form, 'ownerEmail') }, address: addressBody(form, 'address_') };
    void action.mutate(company ? `/companies/${company.id}` : '/companies', company ? 'PATCH' : 'POST', body, onSaved);
  }
  return <><DataState loading={tiers.loading || drivers.loading || references.loading} failure={tiers.failure ?? drivers.failure ?? references.failure} refresh={() => { tiers.refresh(); drivers.refresh(); references.refresh(); }} /><EditorForm title={company ? 'Edit company' : 'Add company'} fields={fields} initial={initial} pending={action.pending} failure={action.failure} onSubmit={submit} onCancel={onClose} /></>;
}
function AddressManager({ companyId, name, onClose, onSaved }: { companyId: string; name: string; onClose: () => void; onSaved: () => void }) {
  const resource = useResource<CompanyResponse>(`/companies/${companyId}`);
  const [editing, setEditing] = useState<CompanyAddressResponse | null>(null);
  const [open, setOpen] = useState(false);
  const action = useMutation();
  return <section className="config-section"><div className="section-toolbar"><h2>Addresses for {name}</h2><div><Button variant="secondary" onClick={() => { setEditing(null); setOpen(true); }}>Add address</Button><Button variant="ghost" onClick={onClose}>Close addresses</Button></div></div><DataState loading={resource.loading} failure={resource.failure} refresh={resource.refresh} /><Feedback failure={action.failure} notice={open ? '' : action.notice} /><Card><div className="table-scroll"><table><thead><tr><th>Address</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{resource.data?.addresses.map((address) => <tr key={address.id}><td>{address.label}{resource.data?.defaultAddressId === address.id && <span className="cell-note">Company default</span>}</td><td>{[address.line1, address.line2, address.city, address.region, address.postalCode, address.country].filter(Boolean).join(', ')}</td><td>{address.active ? 'Active' : 'Inactive'}</td><td><Button variant="ghost" onClick={() => { setEditing(address); setOpen(true); }}>Edit address</Button></td></tr>)}</tbody></table></div></Card>{open && <EditorForm key={editing?.id ?? 'new-address'} title={editing ? 'Edit delivery address' : 'Add delivery address'} fields={[...addressFields, { name: 'active', label: 'Active address', type: 'checkbox', help: 'The default address cannot be deactivated. Choose another default in the company form first.' }]} initial={editing ? { ...editing } : { active: true, country: 'India' }} pending={action.pending} failure={action.failure} onCancel={() => setOpen(false)} onSubmit={(form) => void action.mutate(editing ? `/companies/${companyId}/addresses/${editing.id}` : `/companies/${companyId}/addresses`, editing ? 'PATCH' : 'POST', { ...addressBody(form), active: checked(form, 'active') }, () => { resource.refresh(); onSaved(); setOpen(false); })} />}</section>;
}
