'use client';

import { useState } from 'react';
import type { CompanyResponse, EmployeeImportResult, EmployeeResponse } from '@fernleaf/contracts';
import { Button } from '@/components/ui/button';
import { useReferences } from './catalogue';
import { Card } from '@/components/ui/card';
import { checked, DataState, EditorForm, Feedback, Heading, nullableValue, RecordList, selections, textValue, useMutation, useChoiceResource, type FieldDefinition } from './common';

export function EmployeesScreen({ initialCompanyId = '' }: { initialCompanyId?: string }) {
  const [companyId, setCompanyId] = useState(initialCompanyId);
  const [transfer, setTransfer] = useState<EmployeeResponse | null>(null);
  const [revision, setRevision] = useState(0);
  const companies = useChoiceResource<CompanyResponse>('/companies?page=1&pageSize=100');
  const references = useReferences();
  const fields: FieldDefinition[] = [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Employee email', type: 'email', required: true }, { name: 'phone', label: 'Phone' }, { name: 'companyId', label: 'Company', type: 'select', required: true, choices: (companies.data?.items ?? []).map((company) => ({ value: company.id, label: company.name })), help: 'To move an existing employee, use Transfer. Historical orders keep their original company.' }, { name: 'active', label: 'Active employee', type: 'checkbox' }, { name: 'canChooseAddress', label: 'May choose delivery address', type: 'checkbox' }, { name: 'canChangeTime', label: 'May change delivery time', type: 'checkbox' }, { name: 'canChangePackaging', label: 'May change packaging', type: 'checkbox' }, { name: 'allergenIds', label: 'Allergies', type: 'multiple', choices: (references.data ?? []).filter((value) => value.kind === 'ALLERGEN').map((value) => ({ value: value.id, label: value.name })) }, { name: 'dietaryTagIds', label: 'Dietary preferences', type: 'multiple', choices: (references.data ?? []).filter((value) => value.kind === 'DIETARY_TAG').map((value) => ({ value: value.id, label: value.name })), help: 'Allergies and preferences provide guidance in the menu. They do not certify food safety or automatically filter dishes.' }];
  return <><Heading title="Employees" description="One company per employee, with delivery permissions, allergies and dietary preferences." /><div className="filter-bar"><label htmlFor="employee-company-filter">Company filter</label><select id="employee-company-filter" value={companyId} onChange={(event) => setCompanyId(event.target.value)}><option value="">All companies</option>{companies.data?.items.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></div><DataState loading={companies.loading || references.loading} failure={companies.failure ?? references.failure} refresh={() => { companies.refresh(); references.refresh(); }} /><EmployeeImport companies={companies.data?.items ?? []} defaultCompanyId={companyId} onImported={() => setRevision((value) => value + 1)} /><RecordList<EmployeeResponse> key={`${companyId}-${revision}`} path={`/employees${companyId ? `?companyId=${companyId}` : ''}`} searchParam="search" title="Employees" onSaved={companies.refresh} fields={(row) => row ? fields.filter((field) => field.name !== 'companyId') : fields} defaults={{ active: true, companyId }} initial={(row) => ({ ...row })} payload={(form, row) => ({ ...(!row ? { companyId: textValue(form, 'companyId') } : {}), name: textValue(form, 'name'), email: textValue(form, 'email'), phone: nullableValue(form, 'phone'), active: checked(form, 'active'), canChooseAddress: checked(form, 'canChooseAddress'), canChangeTime: checked(form, 'canChangeTime'), canChangePackaging: checked(form, 'canChangePackaging'), allergenIds: selections(form, 'allergenIds'), dietaryTagIds: selections(form, 'dietaryTagIds') })} columns={[{ label: 'Employee', render: (row) => <><strong>{row.name}</strong><span className="cell-note">{row.email}</span></> }, { label: 'Company', render: (row) => companies.data?.items.find((company) => company.id === row.companyId)?.name ?? 'Company unavailable' }, { label: 'Delivery permissions', render: (row) => [row.canChooseAddress && 'address', row.canChangeTime && 'time', row.canChangePackaging && 'packaging'].filter(Boolean).join(', ') || 'Company defaults' }, { label: 'Status', render: (row) => row.active ? 'Active' : 'Inactive' }]} extra={(row) => <Button variant="ghost" onClick={() => setTransfer(row)}>Transfer</Button>} />{transfer && <TransferForm key={transfer.id} employee={transfer} companies={companies.data?.items ?? []} onClose={() => setTransfer(null)} onSaved={() => { setTransfer(null); setRevision((value) => value + 1); companies.refresh(); }} />}</>;
}
function TransferForm({ employee, companies, onClose, onSaved }: { employee: EmployeeResponse; companies: CompanyResponse[]; onClose: () => void; onSaved: () => void }) {
  const action = useMutation();
  const source = companies.find((company) => company.id === employee.companyId);
  const isOwner = source?.ownerEmployeeId === employee.id;
  return <EditorForm title={`Transfer ${employee.name}`} fields={[{ name: 'companyId', label: 'Destination company', type: 'select', required: true, choices: companies.filter((company) => company.active && company.id !== employee.companyId).map((company) => ({ value: company.id, label: company.name })) }, ...(isOwner ? [{ name: 'replacementOwnerId', label: 'Replacement owner in current company', type: 'select' as const, required: true, choices: (source?.employees ?? []).filter((replacement) => replacement.id !== employee.id && replacement.active).map((replacement) => ({ value: replacement.id, label: `${replacement.name} · ${replacement.email}` })), help: 'The source company must retain an active employee owner.' }] : [])]} pending={action.pending} failure={action.failure} onCancel={onClose} onSubmit={(form) => void action.mutate(`/employees/${employee.id}/transfer`, 'POST', { companyId: textValue(form, 'companyId'), ...(isOwner ? { replacementOwnerId: textValue(form, 'replacementOwnerId') } : {}) }, onSaved)}><p className="section-description">This moves the employee&apos;s future menu and ordering rules. Existing purchase snapshots and billing companies remain unchanged.</p></EditorForm>;
}

const TEMPLATE = 'name,email,phone,can_choose_address,can_change_time,can_change_packaging,allergens,dietary_tags\nAsha Rao,asha.rao@company.example,+91 90000 00000,yes,no,no,Peanuts;Dairy,Vegetarian';
function EmployeeImport({ companies, defaultCompanyId, onImported }: { companies: CompanyResponse[]; defaultCompanyId: string; onImported: () => void }) {
  const [open, setOpen] = useState(false);
  const [companyId, setCompanyId] = useState(defaultCompanyId);
  const [csv, setCsv] = useState('');
  const [fileName, setFileName] = useState('');
  const [result, setResult] = useState<EmployeeImportResult | null>(null);
  const action = useMutation();
  async function run(dryRun: boolean) {
    setResult(null);
    const value = await action.mutate<EmployeeImportResult>('/employees/import', 'POST', { companyId, csv, dryRun });
    if (value) { setResult(value); if (value.created > 0) onImported(); }
  }
  if (!open) return <div className="section-toolbar"><span className="section-description">Add many employees to one company from a CSV file.</span><Button variant="secondary" onClick={() => setOpen(true)}>Import employees from CSV</Button></div>;
  const errors = result?.rows.filter((row) => row.status === 'ERROR') ?? [];
  return <Card className="editor-card"><div className="section-toolbar"><h2>Import employees from CSV</h2><Button variant="secondary" onClick={() => setOpen(false)}>Close import</Button></div>
    <p className="section-description">The first row must be a header. Required columns: <code>name</code>, <code>email</code>. Optional: <code>phone</code>, <code>can_choose_address</code>, <code>can_change_time</code>, <code>can_change_packaging</code> (yes/no, true/false or 1/0; blank means no), <code>allergens</code> and <code>dietary_tags</code> (reference-list names separated by semicolons). Rows with problems are listed by line and skipped; every other row is imported. Existing employees are never changed.</p>
    <pre className="cell-note" style={{ whiteSpace: 'pre-wrap' }}>{TEMPLATE}</pre>
    <div className="form-grid"><label className="form-field" htmlFor="import-company"><span id="import-company-label">Company</span><select id="import-company" aria-labelledby="import-company-label" value={companyId} onChange={(event) => { setCompanyId(event.target.value); setResult(null); }} required><option value="">Choose the company</option>{companies.filter((company) => company.active).map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label>
      <label className="form-field" htmlFor="import-file">CSV file<input id="import-file" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; setResult(null); if (!file) { setCsv(''); setFileName(''); return; } setFileName(file.name); void file.text().then(setCsv); }} /></label></div>
    {fileName && <p className="field-help">{fileName}: {Math.max(csv.split(/\r?\n/).filter((line) => line.trim()).length - 1, 0)} data line(s) read.</p>}
    <Feedback failure={action.failure} />
    <div className="form-actions"><Button type="button" variant="secondary" disabled={!companyId || !csv || action.pending} onClick={() => void run(true)}>{action.pending ? 'Checking...' : 'Check file (no changes)'}</Button><Button type="button" disabled={!companyId || !csv || action.pending} onClick={() => void run(false)}>{action.pending ? 'Importing...' : 'Import valid rows'}</Button></div>
    {result && <div role="status"><p><strong>{result.dryRun ? `Check complete: ${result.valid} of ${result.totalRows} row(s) can be imported, ${result.failed} need fixing.` : `Imported ${result.created} of ${result.totalRows} row(s); ${result.failed} row(s) were skipped.`}</strong></p>
      {errors.length > 0 && <div className="table-scroll"><table><thead><tr><th>Line</th><th>Name</th><th>Email</th><th>What to fix</th></tr></thead><tbody>{errors.map((row) => <tr key={row.line}><td>{row.line}</td><td>{row.name || '—'}</td><td>{row.email || '—'}</td><td><ul>{row.errors.map((error) => <li key={error}>{error}</li>)}</ul></td></tr>)}</tbody></table></div>}</div>}
  </Card>;
}
