'use client';

import { useState } from 'react';
import type { CompanyResponse, EmployeeResponse } from '@fernleaf/contracts';
import { Button } from '@/components/ui/button';
import { useReferences } from './catalogue';
import { checked, DataState, EditorForm, Heading, nullableValue, RecordList, selections, textValue, useMutation, useChoiceResource, type FieldDefinition } from './common';

export function EmployeesScreen({ initialCompanyId = '' }: { initialCompanyId?: string }) {
  const [companyId, setCompanyId] = useState(initialCompanyId);
  const [transfer, setTransfer] = useState<EmployeeResponse | null>(null);
  const [revision, setRevision] = useState(0);
  const companies = useChoiceResource<CompanyResponse>('/companies?page=1&pageSize=100');
  const references = useReferences();
  const fields: FieldDefinition[] = [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Employee email', type: 'email', required: true }, { name: 'phone', label: 'Phone' }, { name: 'companyId', label: 'Company', type: 'select', required: true, choices: (companies.data?.items ?? []).map((company) => ({ value: company.id, label: company.name })), help: 'To move an existing employee, use Transfer. Historical orders keep their original company.' }, { name: 'active', label: 'Active employee', type: 'checkbox' }, { name: 'canChooseAddress', label: 'May choose delivery address', type: 'checkbox' }, { name: 'canChangeTime', label: 'May change delivery time', type: 'checkbox' }, { name: 'canChangePackaging', label: 'May change packaging', type: 'checkbox' }, { name: 'allergenIds', label: 'Allergies', type: 'multiple', choices: (references.data ?? []).filter((value) => value.kind === 'ALLERGEN').map((value) => ({ value: value.id, label: value.name })) }, { name: 'dietaryTagIds', label: 'Dietary preferences', type: 'multiple', choices: (references.data ?? []).filter((value) => value.kind === 'DIETARY_TAG').map((value) => ({ value: value.id, label: value.name })), help: 'Allergies and preferences provide guidance in the menu. They do not certify food safety or automatically filter dishes.' }];
  return <><Heading title="Employees" description="One company per employee, with delivery permissions, allergies and dietary preferences." /><div className="filter-bar"><label htmlFor="employee-company-filter">Company filter</label><select id="employee-company-filter" value={companyId} onChange={(event) => setCompanyId(event.target.value)}><option value="">All companies</option>{companies.data?.items.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></div><DataState loading={companies.loading || references.loading} failure={companies.failure ?? references.failure} refresh={() => { companies.refresh(); references.refresh(); }} /><RecordList<EmployeeResponse> key={`${companyId}-${revision}`} path={`/employees${companyId ? `?companyId=${companyId}` : ''}`} searchParam="search" title="Employees" onSaved={companies.refresh} fields={(row) => row ? fields.filter((field) => field.name !== 'companyId') : fields} defaults={{ active: true, companyId }} initial={(row) => ({ ...row })} payload={(form, row) => ({ ...(!row ? { companyId: textValue(form, 'companyId') } : {}), name: textValue(form, 'name'), email: textValue(form, 'email'), phone: nullableValue(form, 'phone'), active: checked(form, 'active'), canChooseAddress: checked(form, 'canChooseAddress'), canChangeTime: checked(form, 'canChangeTime'), canChangePackaging: checked(form, 'canChangePackaging'), allergenIds: selections(form, 'allergenIds'), dietaryTagIds: selections(form, 'dietaryTagIds') })} columns={[{ label: 'Employee', render: (row) => <><strong>{row.name}</strong><span className="cell-note">{row.email}</span></> }, { label: 'Company', render: (row) => companies.data?.items.find((company) => company.id === row.companyId)?.name ?? 'Company unavailable' }, { label: 'Delivery permissions', render: (row) => [row.canChooseAddress && 'address', row.canChangeTime && 'time', row.canChangePackaging && 'packaging'].filter(Boolean).join(', ') || 'Company defaults' }, { label: 'Status', render: (row) => row.active ? 'Active' : 'Inactive' }]} extra={(row) => <Button variant="ghost" onClick={() => setTransfer(row)}>Transfer</Button>} />{transfer && <TransferForm key={transfer.id} employee={transfer} companies={companies.data?.items ?? []} onClose={() => setTransfer(null)} onSaved={() => { setTransfer(null); setRevision((value) => value + 1); companies.refresh(); }} />}</>;
}
function TransferForm({ employee, companies, onClose, onSaved }: { employee: EmployeeResponse; companies: CompanyResponse[]; onClose: () => void; onSaved: () => void }) {
  const action = useMutation();
  const source = companies.find((company) => company.id === employee.companyId);
  const isOwner = source?.ownerEmployeeId === employee.id;
  return <EditorForm title={`Transfer ${employee.name}`} fields={[{ name: 'companyId', label: 'Destination company', type: 'select', required: true, choices: companies.filter((company) => company.active && company.id !== employee.companyId).map((company) => ({ value: company.id, label: company.name })) }, ...(isOwner ? [{ name: 'replacementOwnerId', label: 'Replacement owner in current company', type: 'select' as const, required: true, choices: (source?.employees ?? []).filter((replacement) => replacement.id !== employee.id && replacement.active).map((replacement) => ({ value: replacement.id, label: `${replacement.name} · ${replacement.email}` })), help: 'The source company must retain an active employee owner.' }] : [])]} pending={action.pending} failure={action.failure} onCancel={onClose} onSubmit={(form) => void action.mutate(`/employees/${employee.id}/transfer`, 'POST', { companyId: textValue(form, 'companyId'), ...(isOwner ? { replacementOwnerId: textValue(form, 'replacementOwnerId') } : {}) }, onSaved)}><p className="section-description">This moves the employee&apos;s future menu and ordering rules. Existing purchase snapshots and billing companies remain unchanged.</p></EditorForm>;
}
