'use client';

import Link from 'next/link';
import { useState } from 'react';
import type { CatalogueDish, CatalogueMenuItem, EmployeeMenuPreview, EmployeeResponse, MenuCategory } from '@fernleaf/contracts';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { checked, DataState, Heading, money, numberValue, RecordList, textValue, useResource, useChoiceResource } from './common';

const diagnosticLabels: Record<string, string> = { CATEGORY_INACTIVE: 'Category is inactive', CATEGORY_HIDDEN: 'Category is hidden for this company', SECRET_DIRECT_LINK_ONLY: 'Secret category is available through its direct link', MENU_ITEM_INACTIVE: 'Menu item is inactive', MENU_ITEM_HIDDEN: 'Menu item is hidden for this company', DISH_INACTIVE: 'Dish is inactive', DISH_PRICE_MISSING: 'Dish has no price in the selected tier', REQUIRED_GROUP_NO_PRICED_OPTION: 'Required option group has no active priced option' };

export function MenuScreen() {
  const [tab, setTab] = useState('categories');
  const categories = useChoiceResource<MenuCategory>('/categories?page=1&pageSize=100');
  const dishes = useChoiceResource<CatalogueDish>('/dishes?page=1&pageSize=100');
  return <><Heading title="Menu" description="Arrange the menu and preview exactly what each employee can order." /><div className="tab-list" role="tablist" aria-label="Menu sections">{[['categories', 'Categories'], ['items', 'Menu items'], ['preview', 'Employee preview']].map(([id, label]) => <Button key={id} role="tab" aria-selected={tab === id} variant={tab === id ? 'primary' : 'secondary'} onClick={() => setTab(id)}>{label}</Button>)}</div>
    {tab === 'categories' && <RecordList<MenuCategory> path="/categories" title="Categories" onSaved={categories.refresh} fields={[{ name: 'name', label: 'Name', required: true }, { name: 'sortOrder', label: 'Display order', type: 'number', min: 0, required: true }, { name: 'secret', label: 'Secret category', type: 'checkbox', help: 'Only shown by a direct staff preview link. Company restrictions and prices still apply.' }, { name: 'active', label: 'Active', type: 'checkbox' }]} defaults={{ active: true, sortOrder: 0 }} initial={(row) => ({ name: row.name, sortOrder: row.sortOrder, secret: row.secret, active: row.active })} payload={(form) => ({ name: textValue(form, 'name'), sortOrder: numberValue(form, 'sortOrder'), secret: checked(form, 'secret'), active: checked(form, 'active') })} columns={[{ label: 'Category', render: (row) => <strong>{row.name}</strong> }, { label: 'Display order', render: (row) => row.sortOrder }, { label: 'Visibility', render: (row) => row.secret ? 'Secret · Direct preview only' : 'Normal navigation' }, { label: 'Status', render: (row) => row.active ? 'Active' : 'Inactive' }]} />}
    {tab === 'items' && <><DataState loading={categories.loading || dishes.loading} failure={categories.failure ?? dishes.failure} refresh={() => { categories.refresh(); dishes.refresh(); }} /><RecordList<CatalogueMenuItem> path="/menu-items" title="Menu items" fields={[{ name: 'categoryId', label: 'Category', type: 'select', required: true, choices: (categories.data?.items ?? []).map((row) => ({ value: row.id, label: row.name })) }, { name: 'dishId', label: 'Dish', type: 'select', required: true, choices: (dishes.data?.items ?? []).map((row) => ({ value: row.id, label: `${row.name} (${row.sku})` })) }, { name: 'sortOrder', label: 'Display order', type: 'number', min: 0, required: true }, { name: 'active', label: 'Active', type: 'checkbox' }]} defaults={{ active: true, sortOrder: 0 }} initial={(row) => ({ categoryId: row.categoryId, dishId: row.dishId, sortOrder: row.sortOrder, active: row.active })} payload={(form) => ({ categoryId: textValue(form, 'categoryId'), dishId: textValue(form, 'dishId'), sortOrder: numberValue(form, 'sortOrder'), active: checked(form, 'active') })} columns={[{ label: 'Dish', render: (row) => <strong>{row.dish.name}</strong> }, { label: 'Category', render: (row) => row.category.name }, { label: 'Display order', render: (row) => row.sortOrder }, { label: 'Status', render: (row) => row.active ? 'Active' : 'Inactive' }]} /></>}
    {tab === 'preview' && <EmployeePreviewPicker categories={categories.data?.items ?? []} />}
  </>;
}
function EmployeePreviewPicker({ categories }: { categories: MenuCategory[] }) {
  const employees = useChoiceResource<EmployeeResponse>('/employees?page=1&pageSize=100');
  const [employeeId, setEmployeeId] = useState('');
  return <section className="config-section"><Card className="editor-card"><h2>Employee menu preview</h2><p className="section-description">The kitchen service resolves the employee&apos;s company tier, active records, company hiding and required option prices. Allergies are warnings; they do not automatically remove food.</p><DataState loading={employees.loading} failure={employees.failure} refresh={employees.refresh} /><div className="form-field"><label htmlFor="preview-employee">Employee</label><select id="preview-employee" value={employeeId} onChange={(event) => setEmployeeId(event.target.value)}><option value="">Choose an employee</option>{employees.data?.items.filter((employee) => employee.active).map((employee) => <option key={employee.id} value={employee.id}>{employee.name} · {employee.email}</option>)}</select></div>{employeeId && <div className="secret-links"><h3>Secret category links</h3>{categories.filter((category) => category.secret).map((category) => <Link key={category.id} href={`/menu/preview/${employeeId}/categories/${category.id}`}>Preview {category.name} &rarr;</Link>)}{!categories.some((category) => category.secret) && <p className="muted">No secret categories configured.</p>}</div>}</Card>{employeeId && <MenuPreview key={employeeId} employeeId={employeeId} />}</section>;
}
export function DirectMenuPreview({ employeeId, categoryId }: { employeeId: string; categoryId: string }) {
  return <><Heading title="Secret category preview" description="A direct category link applies the same company restrictions and price rules as the normal menu." /><Link className="button button-secondary" href="/menu">Return to menu configuration</Link><MenuPreview employeeId={employeeId} categoryId={categoryId} /></>;
}
function MenuPreview({ employeeId, categoryId }: { employeeId: string; categoryId?: string }) {
  const resource = useResource<EmployeeMenuPreview>(categoryId ? `/employees/${employeeId}/menu/categories/${categoryId}` : `/employees/${employeeId}/menu`);
  return <div className="menu-preview"><DataState loading={resource.loading} failure={resource.failure} refresh={resource.refresh} />{resource.data && <><div className="preview-toolbar"><span>Prices in USD · Company tier resolved by the kitchen</span><Button variant="secondary" onClick={resource.refresh}>Refresh preview</Button></div>{resource.data.categories.map((category) => <section className="preview-category" key={category.id}><div className="section-toolbar"><h2>{category.name}</h2>{category.secret && <span className="status-pill">Secret category</span>}</div><div className="menu-grid">{category.dishes.map((dish) => <Card className="menu-dish" key={dish.menuItemId}><div className="dish-price"><h3>{dish.name}</h3><strong>{money(dish.priceMinor)}</strong></div><p>{dish.description}</p><span className="cell-note">{dish.sku} · {dish.source.toLowerCase()} price{dish.minQuantity ? ` · Minimum ${dish.minQuantity}` : ''}</span>{dish.allergyWarnings.length > 0 && <p className="allergy-warning">Allergen warning: {dish.allergyWarnings.join(', ')}</p>}{dish.dietaryTags.length > 0 && <p className="cell-note">Dietary tags: {dish.dietaryTags.join(', ')}</p>}{dish.groups.map((group) => <div className="preview-group" key={group.id}><h4>{group.name} <span>{group.required ? 'Required · Choose one' : 'Optional · Choose up to one'}</span></h4><ul>{group.options.map((option) => <li key={option.id}><span>{option.name}{option.portions.length > 0 && <span className="cell-note"> · {option.portions.map((portion) => `${portion.name} +${money(portion.surchargeMinor)}`).join(' / ')}</span>}{option.allergyWarnings.length > 0 && <span className="allergy-warning"> · {option.allergyWarnings.join(', ')}</span>}</span><span>+{money(option.priceMinor)}</span></li>)}</ul></div>)}</Card>)}</div>{!category.dishes.length && <p className="empty-copy">No available dishes in this category.</p>}</section>)}{!resource.data.categories.length && <Card className="empty-copy">No visible, priced menu items for this employee.</Card>}<Card className="diagnostic-card"><h2>Availability diagnostics</h2><p className="section-description">Excluded items are listed for staff configuration review. Missing prices, hidden items and unpriced required options never appear as purchasable dishes.</p>{resource.data.diagnostics.length ? <ul>{resource.data.diagnostics.map((diagnostic, index) => <li key={`${diagnostic.menuItemId}-${index}`}>{diagnostic.dishName}: {diagnosticLabels[diagnostic.reason] ?? diagnostic.reason}</li>)}</ul> : <p>No excluded items were reported.</p>}</Card></>}</div>;
}
