'use client';

import type { CompanyResponse, EmployeeResponse, ReferenceValueResponse } from '@fernleaf/contracts';
import type { DeliveryChoices } from './builder-input';
import styles from './orders.module.css';

export function OrderDeliveryEditor({ choices, company, employee, packaging, override, disabled, onChange }: {
  choices: DeliveryChoices; company: CompanyResponse | null; employee: EmployeeResponse | null;
  packaging: ReferenceValueResponse[]; override: boolean; disabled: boolean; onChange: (choices: DeliveryChoices) => void;
}) {
  const canAddress = override || employee?.canChooseAddress;
  const canTime = override || employee?.canChangeTime;
  const canPackaging = override || employee?.canChangePackaging;
  const addresses = company?.addresses.filter((address) => address.active) ?? [];
  const defaultAddress = company?.addresses.find((address) => address.id === company.defaultAddressId);
  return <fieldset className={styles.fields} disabled={disabled}><legend>Delivery choices</legend><div className="form-grid">
    <label className="form-field" htmlFor="builder-address"><span id="builder-address-label">Delivery address</span><select id="builder-address" aria-labelledby="builder-address-label" aria-describedby="builder-address-help" value={canAddress ? choices.addressId : ''} disabled={!canAddress || (choices.custom && override)} onChange={(event) => onChange({ ...choices, addressId: event.target.value, custom: false })}><option value="">Company default{defaultAddress ? ` · ${defaultAddress.label}` : ' · Not configured'}</option>{choices.addressId && !addresses.some((address) => address.id === choices.addressId) && <option value={choices.addressId}>Saved address is no longer active</option>}{addresses.map((address) => <option key={address.id} value={address.id}>{address.label} · {address.line1}</option>)}</select><span id="builder-address-help" className="field-help">{canAddress ? 'Choose an active saved address from this company.' : 'This employee must use the current company default address.'}</span></label>
    <label className="form-field" htmlFor="builder-time"><span id="builder-time-label">Delivery time (IST)</span><input id="builder-time" aria-labelledby="builder-time-label" aria-describedby="builder-time-help" type="time" value={canTime ? choices.deliveryTime || company?.deliveryTime || '' : company?.deliveryTime ?? ''} disabled={!canTime} onChange={(event) => onChange({ ...choices, deliveryTime: event.target.value })} /><span id="builder-time-help" className="field-help">{canTime ? 'An empty value uses the company default.' : 'This employee must use the company default time.'}</span></label>
    <label className="form-field" htmlFor="builder-packaging"><span id="builder-packaging-label">Packaging</span><select id="builder-packaging" aria-labelledby="builder-packaging-label" aria-describedby="builder-packaging-help" value={canPackaging ? choices.packaging : ''} disabled={!canPackaging} onChange={(event) => onChange({ ...choices, packaging: event.target.value })}><option value="">Company default</option><option value="none">No packaging</option>{choices.packaging && choices.packaging !== 'none' && !packaging.some((value) => value.id === choices.packaging && value.active) && <option value={choices.packaging}>Saved packaging is no longer active</option>}{packaging.filter((value) => value.active).map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select><span id="builder-packaging-help" className="field-help">{canPackaging ? 'Only active packaging is available.' : 'This employee must use the current company default packaging.'}</span></label>
  </div>{override && <label className={styles.checkbox}><input type="checkbox" checked={choices.custom} onChange={(event) => onChange({ ...choices, custom: event.target.checked })} />Use a custom delivery address for this exception</label>}{choices.custom && override && <div className="form-grid">{(['label', 'line1', 'line2', 'city', 'region', 'postalCode', 'country'] as const).map((name) => <label key={name} className="form-field" htmlFor={`custom-${name}`}>{({ label: 'Address label', line1: 'Street address', line2: 'Address line 2', city: 'City', region: 'State / region', postalCode: 'Postal code', country: 'Country' })[name]}<input id={`custom-${name}`} value={choices.customAddress[name] ?? ''} maxLength={name === 'line1' || name === 'line2' ? 250 : name === 'postalCode' ? 30 : 100} onChange={(event) => onChange({ ...choices, customAddress: { ...choices.customAddress, [name]: event.target.value } })} /></label>)}</div>}{choices.custom && !override && <p className="allergy-warning">This saved custom address requires an explicit Admin exception. Choose a saved company address for an ordinary purchase revision.</p>}{company && <p className={styles.muted}>Company: {company.name} · {company.deliveryMinutes} minute journey · {company.driverInstructions || 'No driver instructions'}.</p>}</fieldset>;
}
